export * as democracy from './democracy/calls'
export * as advisoryCommittee from './advisory-committee/calls'
export * as council from './council/calls'
export * as technicalCommittee from './technical-committee/calls'
export * as bounties from './bounties/calls'
