export * as treasury from './treasury/events'
export * as scheduler from './scheduler/events'
export * as technicalCommittee from './technical-committee/events'
export * as democracy from './democracy/events'
export * as preimage from './preimage/events'
