export * as treasury from './treasury/events'
export * as referenda from './referenda/events'
export * as fellowshipCollective from './fellowship-collective/events'
export * as fellowshipReferenda from './fellowship-referenda/events'
export * as scheduler from './scheduler/events'
export * as preimage from './preimage/events'
export * as bounties from './bounties/events'
export * as childBounties from './child-bounties/events'
