export * as balances from './balances/storage'
export * as treasury from './treasury/storage'
export * as technicalCommittee from './technical-committee/storage'
export * as democracy from './democracy/storage'
export * as preimage from './preimage/storage'
