export * as balances from './balances/storage'
export * as democracy from './democracy/storage'
export * as council from './council/storage'
export * as technicalCommittee from './technical-committee/storage'
export * as preimage from './preimage/storage'
export * as treasury from './treasury/storage'
export * as bounties from './bounties/storage'
export * as childBounties from './child-bounties/storage'
